package fr.grdf.poc.drools.aa;
import fr.grdf.poc.model.*;

rule "demande : ATTENTE_ANALYSE" activation-group "demande-AA"
	when
		demande  : DemandeDTO( statutCourantDemande == DemandeDTO.TypeStatutDemandeEnum.ATTENTE_ANALYSE)
	then
    demande.setStatutCourantDemande(DemandeDTO.TypeStatutDemandeEnum.CLOTURE_ANNULEE);
    update(demande);
	end

rule "demande2 : CLOTURE_ANNULEE" activation-group "demande-AA"
  when
    demande2: DemandeDTO(statutCourantDemande == DemandeDTO.TypeStatutDemandeEnum.CLOTURE_ANNULEE)
  then
    System.out.println ("### AaEgdAnnulerDemande.drl: demande2 has fired up");
  end